name: Release Magisk Module

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Install Zip Tool
      run: sudo apt-get install -y zip

    - name: Read Version from module.prop
      id: read_version
      run: |
        VERSION=$(grep '^version=' module/module.prop | cut -d'=' -f2)
        echo "module_version=$VERSION" >> $GITHUB_ENV

    - name: Create Magisk Module ZIP
      run: |
        mkdir -p release
        cd module # Path to the module directory in your repository
        zip -r9 --compression-method store "../release/install.zip" .

    - name: Commit and Push install.zip to Repository
      run: |
        git config user.name "github-actions"
        git config user.email "actions@github.com"
        cp release/install.zip .
        git add install.zip
        git commit -m "Release module ${{ env.module_version }}"
        git push origin main

    - name: Create Tag and Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git tag ${{ env.module_version }}
        git push origin ${{ env.module_version }}
        gh release create ${{ env.module_version }} install.zip --title "${{ env.module_version }}" --notes "Automatically created release."
